export const GET_PRODUCTS_LIST_PENDING = 'GET_PRODUCTS_LIST_PENDING';
export const GET_PRODUCTS_LIST_SUCCESS = 'GET_PRODUCTS_LIST_SUCCESS';
export const GET_PRODUCTS_LIST_FAILURE = 'GET_PRODUCTS_LIST_FAILURE';

export const GET_AUTHORIZATION_PENDING = 'GET_AUTHORIZATION_PENDING';
export const GET_AUTHORIZATION_SUCCESS = 'GET_AUTHORIZATION_SUCCESS';
export const GET_AUTHORIZATION_FAILURE = 'GET_AUTHORIZATION_FAILURE';

export const GET_REGISTRATION_PENDING = 'GET_REGISTRATION_PENDING';

export const USER_LOGOUT = 'USER_LOGOUT';

export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';

export const CREATE_ORDER_PENDING = 'CREATE_ORDER_PENDING';
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_FAILURE = 'CREATE_ORDER_FAILURE';
export const RESET_ORDER = 'RESET_ORDER';
