export const GET_PRODUCTS_LIST_PENDING = 'GET_PRODUCTS_LIST_PENDING';
export const GET_PRODUCTS_LIST_SUCCESS = 'GET_PRODUCTS_LIST_SUCCESS';
export const GET_PRODUCTS_LIST_FAILURE = 'GET_PRODUCTS_LIST_FAILURE';

export const GET_AUTHORIZATION_PENDING = 'GET_AUTHORIZATION_PENDING';
export const GET_AUTHORIZATION_SUCCESS = 'GET_AUTHORIZATION_SUCCESS';
export const GET_AUTHORIZATION_FAILURE = 'GET_AUTHORIZATION_FAILURE';

export const GET_REGISTRATION_PENDING = 'GET_REGISTRATION_PENDING';

export const ADD_TO_CART = 'ADD_TO_CART';
