export const GET_PRODUCTS_LIST_PENDING = 'GET_PRODUCTS_LIST_PENDING';
export const GET_PRODUCTS_LIST_SUCCESS = 'GET_PRODUCTS_LIST_SUCCESS';
export const GET_PRODUCTS_LIST_FAILURE = 'GET_PRODUCTS_LIST_FAILURE';
